services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend/cgi-bin:/usr/local/apache2/cgi-bin
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./.env:/usr/local/apache2/cgi-bin/zaiseki/.env
      - ./frontend/dist/:/usr/local/apache2/htdocs/zaiseki
      - ./frontend/.htaccess:/usr/local/apache2/htdocs/zaiseki/.htaccess

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data:
